project:
  type: website
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!how-to-build.md"

website:
  title: "HydroMT plugin UWBM"
  repo-url: https://github.com/Deltares-research/hydromt_uwbm
  repo-actions: [source, issue]
  issue-url: https://github.com/Deltares-research/hydromt_uwbm/issues/new/choose
  page-navigation: true
  search:
    location: navbar
    limit: 5
    type: textbox
  page-footer:
    left: |
      Made possible by:
        <a href="https://www.deltares.nl/en" target="_blank" rel="noreferrer noopener">
          <img
            src="/assets/deltares-blue.svg"
            alt="Deltares"
            style="height: 40px;"
          />
        </a>

  navbar:
    logo: assets/logo.jpeg
    title: HydroMT UWBM
    pinned: true
    left:
      - text: "Getting started"
        file: getting_started/index.qmd
      - text: "User guide"
        file: user_guide/index.qmd
      - text: API
        file: api/index.qmd
      - text: "Contributing"
        file: contributing/index.qmd
    right:
      - icon: github
        href: https://github.com/Deltares-research/hydromt_uwbm
        aria-label: GitHub

  sidebar:
    style: docked
    search: true
    contents:
      - section: "Getting started"
        file: getting_started/index.qmd
        contents:
          - text: Installation
            file: getting_started/installation.qmd

      - section: "User guide"
        file: user_guide/index.qmd
        contents:
          - user_guide/uwbm.qmd

      - section: "Contributing"
        file: contributing/index.qmd

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true

bibliography: references.bib
number-sections: true

quartodoc:
  style: pkgdown
  dir: api
  title: API Reference
  package: hydromt_uwbm
  sections:
    - title: Model
      desc: The Model class represents an entire HydroMT plugin UWBM model.
      contents:
        - UWBM
